### PR TITLE
A minor bug fix

### PR DESCRIPTION
**Pull request by preetamozarde3**
Add the image of the user who created the complaint in the complaint card and fixing a bug caused while uploading an image in the file complaint frament.

### CODE REVIEW

**Comment by pulsejet** [comment]
The bug fix seems fine, but *why* do we need the creator's profile pic in the list of complaints? What valuable information does this add from an end user POV?

**Comment by preetamozarde3** [comment]
> The bug fix seems fine, but _why_ do we need the creator's profile pic in the list of complaints? What valuable information does this add from an end user POV?

I thought it would allow the user to better know who posted the complaint. It might also help in distinguishing users with the same name. Do you want me to remove the profile pic?

**Comment by pulsejet** [comment]
I'd revert that. It hardly matters in the first place who made a complaint as long as it's valid considering our use case; a profile pic is just distracting.

**Comment by preetamozarde3** [comment]
> I'd revert that. It hardly matters in the first place who made a complaint as long as it's valid considering our use case; a profile pic is just distracting.

Okay. I've reverted that change.

**Pull request merged**
