### PR TITLE
Maps version Patch for Android 9 and feedbacks from BETA version testing

### PR DESCRIPTION
**Pull request by sshivam95**

### CODE REVIEW

**Comment by sshivam95** [comment]
https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve

Refer this answer

**Comment by sshivam95** [comment]
https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

**Comment by pulsejet** [comment]
Yeah, just saying there will be some "proper" way to do this eventually, probably replacing the Maps SDK entirely with something else, and we should refactor to that if feasible when it comes out. I've already approved the PR in case you missed that.

**Comment by sshivam95** [comment]
I saw that you approved it and appreciate it. Just wanted to have a record of it for future use. No hard feeling bro 👍

**Pull request merged**
